security:
  oauth2:
    client:
      #clientId: bd1c0a783ccdd1c9b9e4
      #clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
      clientId: 3158de19392f86514bf7
      clientSecret: d042df8f0fb67fa253da312dc1181b95f4952989
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
      use-current-uri: true
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false
server:
  context-path: /client
logging.level.org.springframework: INFO
